### ISSUE TITLE
상품파트 업데이트

### ISSUE THREAD

**Issue by niveus323** [whyWhale/shop#8]
1. assets 폴더를 static에 추가하였습니다. application 실행 시 static에서 불러오기 때문에 이동하였는데, 다른 분들께서 templates폴더에서 로딩이 된다면 삭제하겠습니다.

2. 카테고리 추가를 희망합니다.
상위 카테고리(식품, 의류)와 하위 카테고리(가방, 스포츠웨어, 지갑)입니다.
상위 카테고리는 기존 classification 클래스에 등록된 카테고리들을 기반으로 필요한 상위 카테고리입니다.
제가 등록한 클래스가 아니므로 클래스를 직접 변경시 문제가 생길 수 있어 아래 이미지와 같이 변경해주신다면 감사하겠습니다.

![classification 변경](https://user-images.githubusercontent.com/18899404/112519000-492e6c00-8ddd-11eb-8a09-5001dd569a35.PNG)

3. 판매자 도메인 완성 전까지 테스트에 사용하실 url은 다음과 같습니다.
판매자 상품 등록페이지 : /api/product/seller
판매자 상품 리스트 페이지 : /api/product/seller/user
판매자 상품 수정 페이지 : /api/product/seller/{productID}

카테고리별 상품 탐색 페이지 : /api/product/categories/2
상품 상세 페이지 : /api/product/{productID}

data.sql파일을 통해 DB 초기 데이터에 카테고리를 추가하도록 하였습니다.
카테고리 테이블의 변경이 있을 경우 카테고리별 상품 탐색 페이지는 /api/product/categories/{카테고리의 ID}입니다.

4. view와 컨트롤러 연결 과정에서 수정해야 되는 부분이 많이 발생해서 업데이트가 늦어졌습니다.
일단 1개의 카테고리에 한해 상품 등록, 수정, 카테고리별 검색, 상세 페이지까지는 구현하여 업데이트합니다.
토요일까지 다른 카테고리들에 대해서도 완성해서 업데이트하고, 다음주 수요일까지 판매자 도메인 완성해서 업데이트하겠습니다.

**Comment by chaeyoung97** [comment]
확인했습니다~~! 수고하셨어요 👏
1.은 제가 급하게 올리느라 한 폴더에 올렸었는데 저두 이후에 static으로 이동해서 사용중이라 냅두시면 될 것 같아요

**Comment by chaeyoung97** [comment]
![image](https://user-images.githubusercontent.com/47133664/113034594-3ba62700-91cd-11eb-8093-915094d8ea40.png)

상품등록중에 위에와 같이 NPE가 발생하는데 저만 그런건가요?ㅜㅜ
db상에서 image테이블에는 저장되고, \build\resources\main\static\images\폴더에도 이미지 저장은 잘 되고있습니다,,

![image](https://user-images.githubusercontent.com/47133664/113034826-83c54980-91cd-11eb-8c1a-2c1519e67366.png)
응답코드 500받았고 나머지 파라미터들은 잘 요청보내지는 것 확인했습니다
